[package]
name = "divitext"
version = "1.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
log = "0.4.25"
chrono = "0.4.39"
fern = "0.7.1"
ratatui = "0.29.0"
tui-textarea = "0.7.0"
clap = { version = "4.5.32", features = ["cargo"] }

[dev-dependencies]
tempfile = "3.18.0"
